### ISSUE TITLE
Skrypt nie działa poprawnie!!

### ISSUE THREAD

**Issue by losek1** [KrzysztofZawisla/JS_MagdaBeredaFollowersChecker#1]
Skrypt nie działa poprawnie jeśli liczba follow'ujących Magdę przekracza milion

**Comment by KrzysztofZawisla** [comment]
Jestem świadomy tego błędu. Nawet go opisałem w pliku Readme.md. Jeśli ma Pan taki problem proszę zmienić wyrażenie regularne. Pozdrawiam.
